// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Automatically suggests categories for uncategorized expenses using AI.
 *
 * - categorizeExpense - A function that handles the expense categorization process.
 * - CategorizeExpenseInput - The input type for the categorizeExpense function.
 * - CategorizeExpenseOutput - The return type for the categorizeExpense function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import { expenseCategories } from '@/lib/types';

const CategorizeExpenseInputSchema = z.object({
  transactionDescription: z
    .string()
    .describe('La descripción de la transacción sin categorizar.'),
});
export type CategorizeExpenseInput = z.infer<typeof CategorizeExpenseInputSchema>;

const CategorizeExpenseOutputSchema = z.object({
  suggestedCategory: z
    .string()
    .describe('La categoría sugerida por la IA para el gasto.'),
  confidenceScore: z
    .number()
    .describe(
      'Una puntuación entre 0 y 1 que indica la confianza del modelo de IA en la categoría sugerida.'
    ),
});
export type CategorizeExpenseOutput = z.infer<typeof CategorizeExpenseOutputSchema>;

export async function categorizeExpense(input: CategorizeExpenseInput): Promise<CategorizeExpenseOutput> {
  return categorizeExpenseFlow(input);
}

const prompt = ai.definePrompt({
  name: 'categorizeExpensePrompt',
  input: {schema: CategorizeExpenseInputSchema},
  output: {schema: CategorizeExpenseOutputSchema},
  prompt: `Dada la siguiente descripción de transacción, sugiere una categoría para el gasto y una puntuación de confianza entre 0 y 1. La categoría debe ser una de las siguientes: ${expenseCategories.join(', ')}.

Descripción de la Transacción: {{{transactionDescription}}}

Responde en formato JSON con los campos suggestedCategory y confidenceScore.`,
});

const categorizeExpenseFlow = ai.defineFlow(
  {
    name: 'categorizeExpenseFlow',
    inputSchema: CategorizeExpenseInputSchema,
    outputSchema: CategorizeExpenseOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
