// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Automatically suggests categories for uncategorized expenses using AI.
 *
 * - categorizeExpense - A function that handles the expense categorization process.
 * - CategorizeExpenseInput - The input type for the categorizeExpense function.
 * - CategorizeExpenseOutput - The return type for the categorizeExpense function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const CategorizeExpenseInputSchema = z.object({
  transactionDescription: z
    .string()
    .describe('The description of the uncategorized transaction.'),
});
export type CategorizeExpenseInput = z.infer<typeof CategorizeExpenseInputSchema>;

const CategorizeExpenseOutputSchema = z.object({
  suggestedCategory: z
    .string()
    .describe('The AI-suggested category for the expense.'),
  confidenceScore: z
    .number()
    .describe(
      'A score between 0 and 1 indicating the AI model’s confidence in the suggested category.'
    ),
});
export type CategorizeExpenseOutput = z.infer<typeof CategorizeExpenseOutputSchema>;

export async function categorizeExpense(input: CategorizeExpenseInput): Promise<CategorizeExpenseOutput> {
  return categorizeExpenseFlow(input);
}

const prompt = ai.definePrompt({
  name: 'categorizeExpensePrompt',
  input: {schema: CategorizeExpenseInputSchema},
  output: {schema: CategorizeExpenseOutputSchema},
  prompt: `Given the following transaction description, suggest a category for the expense and a confidence score between 0 and 1:

Transaction Description: {{{transactionDescription}}}

Respond in JSON format with the suggestedCategory and confidenceScore fields.`,
});

const categorizeExpenseFlow = ai.defineFlow(
  {
    name: 'categorizeExpenseFlow',
    inputSchema: CategorizeExpenseInputSchema,
    outputSchema: CategorizeExpenseOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
